export const MODAL_CREATE_NAME = "MODAL_CREATE_NAME";
export const MODAL_UPDATE_NAME = "MODAL_UPDATE_NAME";
export const MODAL_DELETE_NAME = "MODAL_DELETE_NAME";
export const MODAL_STATUS_DELETE_NAME = "MODAL_STATUS_DELETE_NAME";
export const MODAL_STATUS_CREATE_NAME = "MODAL_STATUS_CREATE_NAME";

export const MODAL_MORE_NAME = "MODAL_MORE_NAME";
